// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_500.tsx";
import * as $2 from "./routes/about.tsx";
import * as $3 from "./routes/blog.tsx";
import * as $4 from "./routes/blog/[name].tsx";
import * as $5 from "./routes/index.tsx";
import * as $6 from "./routes/releases.tsx";
import * as $7 from "./routes/wip.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/DownloadButton.tsx";
import * as $$2 from "./islands/Footer.tsx";
import * as $$3 from "./islands/HeadCustom.tsx";
import * as $$4 from "./islands/Header.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_500.tsx": $1,
    "./routes/about.tsx": $2,
    "./routes/blog.tsx": $3,
    "./routes/blog/[name].tsx": $4,
    "./routes/index.tsx": $5,
    "./routes/releases.tsx": $6,
    "./routes/wip.tsx": $7,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/DownloadButton.tsx": $$1,
    "./islands/Footer.tsx": $$2,
    "./islands/HeadCustom.tsx": $$3,
    "./islands/Header.tsx": $$4,
  },
  baseUrl: import.meta.url,
};

export default manifest;
